#!/usr/bin/env bash

function convert {
  path=$1
  basepath="converted/$(basename -- $path)"
  mkdir -p $basepath
  echo "> processing directory $path"

  for file in $(find $path/* -maxdepth 0); do
    basename="$(basename -- $file)"
    filename="${basename%.ttf}"
    extension="${basename##*.}"

    if [ "$extension" == "ttf" ] || [ "$extension" == "otf" ]
    then
      echo "  - convert $file into .af"
      ./alright-fonts/afinate --quiet --quality medium --font $file $basepath/$filename.af
    else
      echo "  - copy $file"
      cp $file $basepath/$filename
    fi
  done
}

if [ $# -eq 1 ]; then
  dir=$1
  convert google-fonts/$dir
  echo "  - zipping $dir into $dir\_AlrightFont.zip"
  zip -r zipped/$dir\_AlrightFont.zip converted/$dir
else
  for path in $(find google-fonts/* -maxdepth 0 -type d); do
    convert $path
  done

  echo "> generating zip files"
  mkdir -p zipped
  cd converted
  for dir in *; do
    echo "  - zipping $dir into $dir\_AlrightFont.zip"
    zip -r ../zipped/$dir\_AlrightFont.zip $dir
  done;
  cd ..
fi
